# Generated by Django 5.0.6 on 2025-05-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlagaDeteccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='detections/')),
                ('tipo_plaga', models.CharField(max_length=255)),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
